name: Build and release runtime
on: 
  pull_request:
  workflow_dispatch:
    inputs:
      tag: 
        type: string
        description: Tagged version to build
  push:
    tags:        
      - '**'
env:
  RUNTIME_VERSION: 8.0.5
  RUNTIME_PATCH: jp
  
jobs:
  
  build-linux:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet-buildtools/prereqs:centos-stream8
    steps:
      - name: Check out runtime source code
        uses: actions/checkout@v4
        with:
          ref: refs/tags/v${{env.RUNTIME_VERSION}}-${{env.RUNTIME_PATCH}}
      - name: Build for Linux
        run: ./build.sh -c Release /p:VersionSuffix=${{env.RUNTIME_PATCH}} /p:StabilizePackageVersion=false /p:OfficialBuildId=20201010.1 /p:NativeOptimizationDataSupported=false
      - name : Download dotnet install scripts
        run: wget https://dotnet.microsoft.com/download/dotnet/scripts/v1/dotnet-install.sh
      - name: Retrieve official ASP.Net Core runtime
        run: |
          chmod u+x ./dotnet-install.sh
          mkdir -p artifacts/packages/Release/Shipping/aspnetcore-runtime
          ./dotnet-install.sh --runtime aspnetcore --version ${{env.RUNTIME_VERSION}} --os linux --install-dir artifacts/packages/Release/Shipping/aspnetcore-runtime
      - name: Extract generated runtime artifact, add crossgen, symbols, and AspNetCore runtime
        run: |
          FULL_VERSION=${{env.RUNTIME_VERSION}}-${{env.RUNTIME_PATCH}}
          cd artifacts/packages/Release/Shipping
          mkdir -p dotnet-runtime
          cd dotnet-runtime
          tar -xzvf ../dotnet-runtime-${FULL_VERSION}-linux-x64.tar.gz
          cd shared/Microsoft.NETCore.App/${FULL_VERSION}
          tar -xzvf ../../../../dotnet-crossgen2-${FULL_VERSION}-linux-x64.tar.gz
          tar -xzvf ../../../../dotnet-nethost-symbols-linux-x64-${FULL_VERSION}.tar.gz
          cd ../../../..
          cp -R aspnetcore-runtime/shared/Microsoft.AspNetCore.App dotnet-runtime/shared/Microsoft.AspNetCore.App
          mv dotnet-runtime/shared/Microsoft.AspNetCore.App/${{env.RUNTIME_VERSION}} dotnet-runtime/shared/Microsoft.AspNetCore.App/${FULL_VERSION}
          sed -i "s/${{env.RUNTIME_VERSION}}/${FULL_VERSION}/g" dotnet-runtime/shared/Microsoft.AspNetCore.App/${FULL_VERSION}/Microsoft.AspNetCore.App.runtimeconfig.json
          cd dotnet-runtime
          tar -zcvf ../aspnetcore-runtime-${FULL_VERSION}-linux-x64.tar.gz .
      - name: Upload runtime artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-runtime
          path: artifacts/packages/Release/Shipping/aspnetcore-runtime-${{env.RUNTIME_VERSION}}-${{env.RUNTIME_PATCH}}-linux-x64.tar.gz
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Check out runtime source code
        uses: actions/checkout@v4
        with:
          ref: refs/tags/v${{env.RUNTIME_VERSION}}-${{env.RUNTIME_PATCH}}
      - name: Build CLR for Windows
        run: .\build.cmd clr -c Release /p:OfficialBuildId=20201010.1
      - name: Upload mscordaccore artifact
        uses: actions/upload-artifact@v4
        with:
          name: mscordaccore.dll
          path: artifacts/bin/coreclr/Linux.x64.Release/x64/mscordaccore.dll
  package-and-release:
    runs-on: ubuntu-latest
    needs: 
      - build-linux
      - build-windows
    steps:
      - name: Download .Net runtime artifact
        uses: actions/download-artifact@v4
        with:
          name: linux-runtime
          path: .
      - name: Download mscordaccore artifact
        uses: actions/download-artifact@v4
        with:
          name: mscordaccore.dll
          path: .
      
      #TODO Extract dotnet runtime artifact and inject official AspNetCore artifact
      #TODO Package new runtime containing ASPNetCore
      - name: Create release
        uses: softprops/action-gh-release@v2
        #if: startsWith(github.ref, 'refs/tags/')
        with:
          name: v${{env.RUNTIME_VERSION}}-${{env.RUNTIME_PATCH}}
          body: Release created from GitHub actions
          files: | 
            dotnet-runtime-${{env.RUNTIME_VERSION}}-${{env.RUNTIME_PATCH}}-linux-x64.tar.gz
            mscordaccore.dll
          draft: true
  
  
