name: Test passing variables between jobs
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag: 
        type: string
        description: Tagged version to build
  push:
    tags:        
      - '**'

  
jobs:
  env-variables:
    outputs:
      runtime-version: ${{ steps.set-env.outputs.runtime-version }}
      runtime-patch: ${{ steps.set-env.outputs.runtime-patch }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract runtime variables from workflow inputs
        id: set-env
        run: |
          [ -n "${{github.ref}}" ] && TAG="${{github.ref}}"
          [ -n "${{github.event.inputs.tag}}" ] && TAG="/refs/tags/${{github.event.inputs.tag}}"
          regex="refs\/.*\/(.*)-(.*)"
          if [[ "refs/tags/v0.8.5-criteo1" =~ $regex ]]
          then
            RUNTIME_VERSION=${BASH_REMATCH[1]}
            RUNTIME_PATCH=${BASH_REMATCH[2]}
          else
            RUNTIME_VERSION=dev
            RUNTIME_PATCH=dev
          fi        
          
          echo runtime-version=${RUNTIME_VERSION} >> $GITHUB_OUTPUT
          echo runtime-patch=${RUNTIME_PATCH} >> $GITHUB_OUTPUT
  use-env-variables:
    runs-on: ubuntu-latest
    needs: env-variables
    steps:
      - name: Get output variables from previous job
        run: |
          echo "Runtime version = ${{needs.env-variables.outputs.runtime-version}}
          echo "Runtime patch = ${{needs.env-variables.outputs.runtime-patch}}
        
