name: Test passing variables between jobs
on:
  pull_request:
  workflow_dispatch:
    inputs:
      tag: 
        type: string
        description: Tagged version to build
  push:
    tags:        
      - '**'

  
jobs:
  env-variables:
    outputs:
      runtime-version: ${{ steps.set-env.outputs.runtime-version }}
      runtime-patch: ${{ steps.set-env.outputs.runtime-patch }}
    runs-on: ubuntu-latest
    steps:
      - name: Extract runtime variables from workflow inputs
        id: set-env
        run: |
          [ -n "${{github.ref}}" ] && TAG = "${{github.ref}}"
          [ -n "${{github.event.inputs.tag}}" ] && TAG = "${{github.event.inputs.tag}}"

          echo TAG = $TAG
          
          
          echo runtime-version=8.0.5 >> $GITHUB_OUTPUT
          echo runtime-patch=patch >> $GITHUB_OUTPUT
  use-env-variables:
    runs-on: ubuntu-latest
    needs: env-variables
    steps:
      - name: Get output variables from previous job
        run: |
          echo "Runtime version = ${{needs.env-variables.outputs.runtime-version}}
          echo "Runtime patch = ${{needs.env-variables.outputs.runtime-patch}}
        
